services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pivot-ui
    ports:
      - "80:80"
    environment:
      PIVOT_API_URL: ${PIVOT_API_URL:-http://localhost:8080}
    restart: unless-stopped
