sonar.projectKey=PIVOT-PLATFORM_PIVOT-UI
sonar.organization=pivot-platform
sonar.projectName=PIVOT-PLATFORM_PIVOT-UI

sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*.spec.ts

sonar.javascript.lcov.reportPaths=coverage/lcov.info

sonar.exclusions=**/node_modules/**,dist/**,coverage/**,**/*.spec.ts
sonar.test.exclusions=**/node_modules/**,dist/**

sonar.sourceEncoding=UTF-8
